config/routes.rb
Rails.application.routes.draw do
  root to: 'shows#index'
  resources :shows
  resources :actors
end

app/models/actor.rb
class Actor < ApplicationRecord
  belongs_to :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :shows
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :season
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :shows
end

app/models/screenwriter.rb
class Screenwriter < ApplicationRecord
  has_many :shows
end

app/models/season.rb
class Season < ApplicationRecord
  belongs_to :show
  has_many :episodes
end

app/models/show.rb
class Show < ApplicationRecord
  has_many :actors
  has_many :episodes
  has_many :seasons
  belongs_to :screenwriter
  belongs_to :director
  belongs_to :genre

  def show_finished_at
    finished_at.present? ? finished_at.year : 'N/A'
  end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
    @actors = Actor.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]

  # GET /episodes
  def index
    @episodes = Episode.all
  end

  # GET /episodes/1
  def show
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes
  def create
    @episode = Episode.new(episode_params)

    if @episode.save
      redirect_to @episode, notice: 'Episode was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /episodes/1
  def update
    if @episode.update(episode_params)
      redirect_to @episode, notice: 'Episode was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /episodes/1
  def destroy
    @episode.destroy
    redirect_to episodes_url, notice: 'Episode was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def episode_params
      params.require(:episode).permit(:title, :season_id, :episode_number)
    end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: [:show, :edit, :update, :destroy]

  # GET /seasons
  def index
    @seasons = Season.all
  end

  # GET /seasons/1
  def show
  end

  # GET /seasons/new
  def new
    @season = Season.new
  end

  # GET /seasons/1/edit
  def edit
  end

  # POST /seasons
  def create
    @season = Season.new(season_params)

    if @season.save
      redirect_to @season, notice: 'Season was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /seasons/1
  def update
    if @season.update(season_params)
      redirect_to @season, notice: 'Season was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /seasons/1
  def destroy
    @season.destroy
    redirect_to seasons_url, notice: 'Season was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = Season.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def season_params
      params.require(:season).permit(:title, :show_id, :started_at)
    end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :edit, :update, :destroy]

  def index
    @shows = Show.all
  end

  def show
  end

  def new
    @show = Show.new
  end

  def edit
  end

  def create
    @show = Show.new(show_params)

    if @show.save
      redirect_to @show, notice: 'Show was successfully created.'
    else
      render :new
    end
  end

  def update
    if @show.update(show_params)
      redirect_to @show, notice: 'Show was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @show.destroy
    redirect_to shows_url, notice: 'Show was successfully destroyed.'
  end

  private
    def set_show
      @show = Show.find(params[:id])
    end

    def show_params
      params.require(:show).permit(:title, :started_at, :finished_at, :description, :director_id, :screenwriter_id, :is_finished, :genre_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/actors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Actors</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
    </tr>
  </thead>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.full_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/episodes/_form.html.erb
<%= form_with(model: episode, local: true) do |form| %>
  <% if episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% episode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :season_id %>
    <%= form.number_field :season_id %>
  </div>

  <div class="field">
    <%= form.label :episode_number %>
    <%= form.number_field :episode_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Episodes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Season</th>
      <th>Episode number</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= episode.title %></td>
        <td><%= episode.season_id %></td>
        <td><%= episode.episode_number %></td>
        <td><%= link_to 'Show', episode %></td>
        <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/new.html.erb
<h1>New Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @episode.title %>
</p>

<p>
  <strong>Season:</strong>
  <%= @episode.season_id %>
</p>

<p>
  <strong>Episode number:</strong>
  <%= @episode.episode_number %>
</p>

<%= link_to 'Edit', edit_episode_path(@episode) %> |
<%= link_to 'Back', episodes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kinster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'shared/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/seasons/_form.html.erb
<%= form_with(model: season, local: true) do |form| %>
  <% if season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
      <% season.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :show_id %>
    <%= form.number_field :show_id %>
  </div>

  <div class="field">
    <%= form.label :started_at %>
    <%= form.datetime_select :started_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/seasons/edit.html.erb
<h1>Editing Season</h1>

<%= render 'form', season: @season %>

<%= link_to 'Show', @season %> |
<%= link_to 'Back', seasons_path %>

app/views/seasons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seasons</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Show</th>
      <th>Started at</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @seasons.each do |season| %>
      <tr>
        <td><%= season.title %></td>
        <td><%= season.show_id %></td>
        <td><%= season.started_at %></td>
        <td><%= link_to 'Show', season %></td>
        <td><%= link_to 'Edit', edit_season_path(season) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Season', new_season_path %>

app/views/seasons/new.html.erb
<h1>New Season</h1>

<%= render 'form', season: @season %>

<%= link_to 'Back', seasons_path %>

app/views/seasons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @season.title %>
</p>

<p>
  <strong>Show:</strong>
  <%= @season.show_id %>
</p>

<p>
  <strong>Started at:</strong>
  <%= @season.started_at %>
</p>

<%= link_to 'Edit', edit_season_path(@season) %> |
<%= link_to 'Back', seasons_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Kinster', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Shows', shows_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Actors', actors_path, class: 'nav-link' %>
      </li>
  </div>
</nav>

app/views/shows/_form.html.erb
<%= form_with(model: show, local: true) do |form| %>
  <% if show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :started_at %>
    <%= form.datetime_select :started_at %>
  </div>

  <div class="field">
    <%= form.label :finished_at %>
    <%= form.datetime_select :finished_at %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :genre_id %>
    <%= form.collection_select :genre_id, Genre.all, :id, :title %>
  </div>

  <div class="field">
    <%= form.label :director_id %>
    <%= form.collection_select :director_id, Director.all, :id, :full_name %>
  </div>

  <div class="field">
    <%= form.label :screenwriter_id %>
    <%= form.collection_select :screenwriter_id, Screenwriter.all, :id, :full_name %>
  </div>

  <div class="field">
    <%= form.label :is_finished %>
    <%= form.check_box :is_finished %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shows/edit.html.erb
<h1>Editing Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shows</h1>

<table class='table table-bordered table-hover'>
  <thead>
    <tr>
      <th>Title</th>
    </tr>
  </thead>

  <tbody>
    <% @shows.each do |show| %>
      <tr>
        <td><%= link_to show.title, show %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Show', new_show_path %>

app/views/shows/new.html.erb
<h1>New Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Back', shows_path %>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>


<h1 class='h2'><%= @show.title %></h1>

<%= link_to 'Edit', edit_show_path(@show) %>

<div class="row">
  <div class="col-md-4">
    <h4>Metadata</h4>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Genre: <%= @show.genre.title %></li>
      <li class="list-group-item">Screenwriter: <%= @show.screenwriter.full_name %></li>
      <li class="list-group-item">Director: <%= @show.director.full_name %></li>
      <li class="list-group-item">Started at: <%= @show.started_at.year %></li>
      <li class="list-group-item">Finished at: <%= @show.show_finished_at %></li>
    </ul>
  </div>

  <div class="col-md-4">
    <h4>Actors</h4>
    <ul class="list-group list-group-flush">
      <% @show.actors.each do |actor| %>
        <li class='list-group-item'><%= actor.full_name %></li>
      <% end %>
    </ul>
  </div>

  <div class="col-md-4">
    <h4>Seasons</h4>
    <% @show.seasons.each do |season| %>
      <h6 class="mb-1"><%= season.title %></h6>
      <ul class='list-group list-group-flush mb-5'>
        <% season.episodes.each do |episode| %>
          <li class="list-group-item"><%= episode.title %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="col-md-12">
    <div class="jumbotron">
      <h4>Description</h4>
      <p>
        <%= @show.description %>
      </p>
    </div>
  </div>
</div>